CREATE TABLE IF NOT EXISTS resume (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255),
    attachment VARCHAR(255),
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);